import { AdminPage, Button, Card, DataTableCard, MetricCard, Table, TableCell, TableHead, ToneBadge } from "@/components/admin/shared";
import { Input } from "@/components/ui/input";
import { PERMISSIONS } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/require-permission";
import { prisma } from "@/lib/prisma";
import { approvePayrollAdjustmentAction, createPayrollAdjustmentAction, createPayrollRunAction, transitionPayrollRunAction } from "../actions";

const label = "grid gap-1 text-sm font-semibold text-slate-700";
const usd = (value: { toFixed(digits: number): string }) => `$${value.toFixed(2)}`;

export default async function PayrollPage() {
  await requirePermission(PERMISSIONS.PAYROLL_MANAGE);
  const [staff, adjustments, runs] = await Promise.all([
    prisma.user.findMany({ where: { employmentProfile: { is: { status: "ACTIVE" } } }, orderBy: { fullName: "asc" }, select: { id: true, fullName: true } }),
    prisma.payrollAdjustment.findMany({ include: { worker: { select: { fullName: true } } }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.payrollRun.findMany({ include: { lines: { include: { worker: { select: { fullName: true } } } } }, orderBy: { createdAt: "desc" }, take: 24 }),
  ]);
  const finalized = runs.filter((run) => run.status === "FINALIZED");
  const paid = finalized.reduce((sum, run) => sum + run.lines.reduce((lineSum, line) => lineSum + Number(line.netPay), 0), 0);
  return <AdminPage title="Payroll" description="Admin-only payroll adjustments, previews, approval, finalization and voiding.">
    <section className="grid gap-4 sm:grid-cols-3"><MetricCard label="Active profiles" value={staff.length}/><MetricCard label="Pending adjustments" value={adjustments.filter((row) => !row.approvedAt).length}/><MetricCard label="Finalized total" value={`$${paid.toFixed(2)}`}/></section>
    <section className="grid gap-5 xl:grid-cols-2"><Card className="p-5"><h2 className="mb-4 font-bold">Add payroll adjustment</h2><form action={createPayrollAdjustmentAction} className="grid gap-3 sm:grid-cols-2"><label className={label}>Worker<select name="workerId" className="h-9 rounded-lg border px-3">{staff.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><label className={label}>Type<select name="type" className="h-9 rounded-lg border px-3"><option value="BONUS">Bonus</option><option value="OVERTIME">Overtime pay</option><option value="ADVANCE">Advance</option><option value="ABSENCE_DEDUCTION">Absence deduction</option><option value="CORRECTION">Correction</option></select></label><label className={label}>Period start<Input name="periodStart" type="date" required/></label><label className={label}>Period end<Input name="periodEnd" type="date" required/></label><label className={label}>Amount (USD)<Input name="amount" type="number" min="0.01" step="0.01" required/></label><label className={label}>Reason<Input name="reason" minLength={3} maxLength={500} required/></label><Button type="submit">Record adjustment</Button></form></Card>
      <Card className="p-5"><h2 className="mb-4 font-bold">Create payroll preview</h2><form action={createPayrollRunAction} className="grid gap-3 sm:grid-cols-2"><label className={label}>Period start<Input name="periodStart" type="date" required/></label><label className={label}>Period end<Input name="periodEnd" type="date" required/></label><Button type="submit">Create draft run</Button></form><p className="mt-3 text-xs text-slate-500">Only approved attendance and approved adjustments are snapshotted. Finalized periods cannot overlap.</p></Card></section>
    <DataTableCard><Table><thead><tr><TableHead>Worker</TableHead><TableHead>Type</TableHead><TableHead>Period</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></tr></thead><tbody>{adjustments.length ? adjustments.map((row) => <tr key={row.id}><TableCell className="font-semibold">{row.worker.fullName}</TableCell><TableCell>{row.type}</TableCell><TableCell>{row.periodStart.toLocaleDateString()} – {row.periodEnd.toLocaleDateString()}</TableCell><TableCell>{usd(row.amount)}</TableCell><TableCell><ToneBadge tone={row.approvedAt ? "green" : "amber"}>{row.approvedAt ? "APPROVED" : "PENDING"}</ToneBadge></TableCell><TableCell>{!row.approvedAt ? <form action={approvePayrollAdjustmentAction}><input type="hidden" name="adjustmentId" value={row.id}/><Button size="sm" variant="outline">Approve</Button></form> : "—"}</TableCell></tr>) : <tr><TableCell colSpan={6} className="py-10 text-center">No payroll adjustments.</TableCell></tr>}</tbody></Table></DataTableCard>
    <div className="space-y-4">{runs.map((run) => <Card className="p-5" key={run.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">{run.periodStart.toLocaleDateString()} – {run.periodEnd.toLocaleDateString()}</h2><ToneBadge tone={run.status === "FINALIZED" ? "green" : run.status === "VOIDED" ? "red" : "blue"}>{run.status}</ToneBadge></div><div className="flex gap-2">{run.status === "DRAFT" ? <form action={transitionPayrollRunAction}><input type="hidden" name="runId" value={run.id}/><input type="hidden" name="action" value="APPROVE"/><Button size="sm">Approve</Button></form> : null}{run.status === "APPROVED" ? <form action={transitionPayrollRunAction}><input type="hidden" name="runId" value={run.id}/><input type="hidden" name="action" value="FINALIZE"/><Button size="sm">Finalize</Button></form> : null}{run.status !== "VOIDED" ? <form action={transitionPayrollRunAction}><input type="hidden" name="runId" value={run.id}/><input type="hidden" name="action" value="VOID"/><input type="hidden" name="reason" value="Voided from payroll administration"/><Button size="sm" variant="outline">Void</Button></form> : null}</div></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th>Worker</th><th>Base</th><th>Overtime</th><th>Additions</th><th>Deductions</th><th>Net</th></tr></thead><tbody>{run.lines.map((line) => <tr className="border-t" key={line.id}><td className="py-2 font-semibold">{line.worker.fullName}</td><td>{usd(line.basePay)}</td><td>{usd(line.overtimePay)}</td><td>{usd(line.additions)}</td><td>{usd(line.deductions)}</td><td className="font-bold">{usd(line.netPay)}</td></tr>)}</tbody></table></div></Card>)}</div>
  </AdminPage>;
}
