CREATE TYPE "CompensationType" AS ENUM ('DAILY', 'MONTHLY');
CREATE TYPE "EmploymentStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'ENDED');
CREATE TYPE "ScheduledShiftStatus" AS ENUM ('SCHEDULED', 'CANCELLED', 'COMPLETED');
CREATE TYPE "ClockEventType" AS ENUM ('IN', 'OUT');
CREATE TYPE "AttendanceStatus" AS ENUM ('PENDING', 'PRESENT', 'ABSENT', 'REJECTED');
CREATE TYPE "PayrollAdjustmentType" AS ENUM ('BONUS', 'ADVANCE', 'ABSENCE_DEDUCTION', 'CORRECTION', 'OVERTIME');
CREATE TYPE "PayrollRunStatus" AS ENUM ('DRAFT', 'APPROVED', 'FINALIZED', 'VOIDED');

CREATE TABLE "EmploymentProfile" (
  "id" TEXT NOT NULL, "userId" TEXT NOT NULL, "compensationType" "CompensationType" NOT NULL,
  "dailyRate" DECIMAL(14,2), "monthlySalary" DECIMAL(14,2), "effectiveFrom" DATE NOT NULL,
  "effectiveTo" DATE, "status" "EmploymentStatus" NOT NULL DEFAULT 'ACTIVE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "EmploymentProfile_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "EmploymentProfile_userId_key" UNIQUE ("userId"),
  CONSTRAINT "EmploymentProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "EmploymentProfile_compensation_check" CHECK (("compensationType" = 'DAILY' AND "dailyRate" IS NOT NULL AND "monthlySalary" IS NULL) OR ("compensationType" = 'MONTHLY' AND "monthlySalary" IS NOT NULL AND "dailyRate" IS NULL))
);
CREATE INDEX "EmploymentProfile_status_effectiveFrom_idx" ON "EmploymentProfile"("status", "effectiveFrom");
CREATE TABLE "AttendancePolicy" ("id" TEXT NOT NULL DEFAULT 'default', "shiftMinutes" INTEGER NOT NULL DEFAULT 480, "graceMinutes" INTEGER NOT NULL DEFAULT 10, "overtimeThresholdMinutes" INTEGER NOT NULL DEFAULT 480, "timezone" TEXT NOT NULL DEFAULT 'Africa/Nairobi', "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AttendancePolicy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ScheduledShift" ("id" TEXT NOT NULL, "workerId" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3) NOT NULL, "station" "Station", "status" "ScheduledShiftStatus" NOT NULL DEFAULT 'SCHEDULED', "createdByUserId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ScheduledShift_pkey" PRIMARY KEY ("id"), CONSTRAINT "ScheduledShift_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "ScheduledShift_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "ScheduledShift_workerId_startsAt_idx" ON "ScheduledShift"("workerId", "startsAt"); CREATE INDEX "ScheduledShift_status_startsAt_idx" ON "ScheduledShift"("status", "startsAt");
CREATE TABLE "ClockEvent" ("id" TEXT NOT NULL, "workerId" TEXT NOT NULL, "type" "ClockEventType" NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ClockEvent_pkey" PRIMARY KEY ("id"), CONSTRAINT "ClockEvent_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE); CREATE INDEX "ClockEvent_workerId_occurredAt_idx" ON "ClockEvent"("workerId", "occurredAt");
CREATE TABLE "AttendanceRecord" ("id" TEXT NOT NULL, "workerId" TEXT NOT NULL, "scheduledShiftId" TEXT, "businessDate" DATE NOT NULL, "status" "AttendanceStatus" NOT NULL DEFAULT 'PENDING', "clockInAt" TIMESTAMP(3), "clockOutAt" TIMESTAMP(3), "workedMinutes" INTEGER NOT NULL DEFAULT 0, "lateMinutes" INTEGER NOT NULL DEFAULT 0, "approvedOvertimeMinutes" INTEGER NOT NULL DEFAULT 0, "absenceReason" TEXT, "approvedByUserId" TEXT, "approvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AttendanceRecord_pkey" PRIMARY KEY ("id"), CONSTRAINT "AttendanceRecord_scheduledShiftId_key" UNIQUE ("scheduledShiftId"), CONSTRAINT "AttendanceRecord_workerId_businessDate_key" UNIQUE ("workerId", "businessDate"), CONSTRAINT "AttendanceRecord_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "AttendanceRecord_scheduledShiftId_fkey" FOREIGN KEY ("scheduledShiftId") REFERENCES "ScheduledShift"("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "AttendanceRecord_approvedByUserId_fkey" FOREIGN KEY ("approvedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE); CREATE INDEX "AttendanceRecord_businessDate_status_idx" ON "AttendanceRecord"("businessDate", "status");
CREATE TABLE "PayrollAdjustment" ("id" TEXT NOT NULL, "workerId" TEXT NOT NULL, "periodStart" DATE NOT NULL, "periodEnd" DATE NOT NULL, "type" "PayrollAdjustmentType" NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "reason" TEXT NOT NULL, "createdByUserId" TEXT NOT NULL, "approvedByUserId" TEXT, "approvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PayrollAdjustment_pkey" PRIMARY KEY ("id"), CONSTRAINT "PayrollAdjustment_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "PayrollAdjustment_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "PayrollAdjustment_approvedByUserId_fkey" FOREIGN KEY ("approvedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE); CREATE INDEX "PayrollAdjustment_workerId_periodStart_periodEnd_idx" ON "PayrollAdjustment"("workerId", "periodStart", "periodEnd");
CREATE TABLE "PayrollRun" ("id" TEXT NOT NULL, "periodStart" DATE NOT NULL, "periodEnd" DATE NOT NULL, "status" "PayrollRunStatus" NOT NULL DEFAULT 'DRAFT', "createdByUserId" TEXT NOT NULL, "approvedByUserId" TEXT, "approvedAt" TIMESTAMP(3), "finalizedByUserId" TEXT, "finalizedAt" TIMESTAMP(3), "voidedAt" TIMESTAMP(3), "voidReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PayrollRun_pkey" PRIMARY KEY ("id"), CONSTRAINT "PayrollRun_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "PayrollRun_approvedByUserId_fkey" FOREIGN KEY ("approvedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "PayrollRun_finalizedByUserId_fkey" FOREIGN KEY ("finalizedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE); CREATE INDEX "PayrollRun_status_periodStart_periodEnd_idx" ON "PayrollRun"("status", "periodStart", "periodEnd");
CREATE TABLE "PayrollLine" ("id" TEXT NOT NULL, "payrollRunId" TEXT NOT NULL, "workerId" TEXT NOT NULL, "compensationType" "CompensationType" NOT NULL, "basePay" DECIMAL(14,2) NOT NULL, "overtimePay" DECIMAL(14,2) NOT NULL DEFAULT 0, "additions" DECIMAL(14,2) NOT NULL DEFAULT 0, "deductions" DECIMAL(14,2) NOT NULL DEFAULT 0, "netPay" DECIMAL(14,2) NOT NULL, "attendanceDays" INTEGER NOT NULL DEFAULT 0, "overtimeMinutes" INTEGER NOT NULL DEFAULT 0, "snapshot" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PayrollLine_pkey" PRIMARY KEY ("id"), CONSTRAINT "PayrollLine_payrollRunId_workerId_key" UNIQUE ("payrollRunId", "workerId"), CONSTRAINT "PayrollLine_payrollRunId_fkey" FOREIGN KEY ("payrollRunId") REFERENCES "PayrollRun"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "PayrollLine_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "PayrollLine_finalized_period_worker_unique" ON "PayrollLine"("workerId", "payrollRunId");
