// prisma/seed.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("Missing DIRECT_URL or DATABASE_URL for Prisma seed.");
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function main() {
  // -----------------------------
  // Users
  // -----------------------------
 ;

  // -----------------------------
  // Tables
  // -----------------------------
  await prisma.table.createMany({
    data: Array.from({ length: 40 }).map((_, i) => ({
      name: `T${i + 1}`,
      isActive: false,
    })),
    skipDuplicates: true,
  });

  const tableRows = await prisma.table.findMany({ orderBy: { name: "asc" } });

  // -----------------------------
  // Categories
  // -----------------------------
  const drinks = await prisma.category.create({
    data: {
      name: "Drinks",
      sortOrder: 3,
      station: "CABITAAN",
    },
  });

  const FastFood = await prisma.category.create({
    data: {
      name: "Fast Food",
      sortOrder: 4,
      station: "FAST_FOOD",
    },
  });

  const SomailFood = await prisma.category.create({
    data: {
      name: "SomailFood",
      sortOrder: 5,
      station: "CUNTO_SOOMAALI",
    },
  });

  const Macmacaan = await prisma.category.create({
    data: {
      name: "Macmacaan",
      sortOrder: 2,
      station: "CABITAAN",
    },
  });

  const Tea = await prisma.category.create({
    data: {
      name: "Tea",
      sortOrder: 1,
      station: "CABITAAN",
    },
  });

  const Coffee = await prisma.category.create({
    data: {
      name: "Coffee",
      sortOrder: 6,
      station: "CABITAAN",
    },
  });

  const Store = await prisma.category.create({
    data: {
      name: "Store",
      sortOrder: 7,
    },
  });

  // -----------------------------
  // Products
  // -----------------------------

  await prisma.$transaction([
    prisma.product.create({
      data: {
        name: "Coffee",
        sku: "DRK-001",
        price: 350,
        cost: 0,
        categoryId: drinks.id,
        isActive: true,
        trackStock: false,
        stockQty: 0,
      },
    }),
    prisma.product.create({
      data: {
        name: "Latte",
        sku: "DRK-002",
        price: 4.5,
        cost: 0,
        categoryId: drinks.id,
        isActive: true,
      },
    }),
    prisma.product.create({
      data: {
        name: "Cappuccino",
        sku: "DRK-003",
        price: 5,
        cost: 0,
        categoryId: drinks.id,
        isActive: true,
      },
    }),
    prisma.product.create({
      data: {
        name: "Croissant",
        sku: "FOD-001",
        price: 4.5,
        cost: 0,
        categoryId: SomailFood.id,
        isActive: true,
      },
    }),
    prisma.product.create({
      data: {
        name: "Sandwich",
        sku: "FOD-002",
        price: 8.5,
        cost: 0,
        categoryId: SomailFood.id,
        isActive: true,
      },
    }),
    prisma.product.create({
      data: {
        name: "Cheesecake",
        sku: "FOD-003",
        price: 6,
        cost: 0,
        categoryId: SomailFood.id,
        isActive: true,
      },
    }),
  ]);

  const productSeedData = [
    {
      name: "1 Meat Burger oo Rooti Yar",
      sku: "10101",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "2 Rooti kaliya",
      sku: "10219",
      price: 0.4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "3 half saldaato tuno ah",
      sku: "10088",
      price: 0,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "7up",
      sku: "10066",
      price: 0.9,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Al Cayn(800ml)",
      sku: "10238",
      price: 4.4,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Al-Caafiyah Pure Honey",
      sku: "10095",
      price: 2,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Al-Cayn(350Ml)",
      sku: "10004",
      price: 4.4,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Al-Diyar",
      sku: "10070",
      price: 2.7,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Amino Tissue",
      sku: "10103",
      price: 2,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Avocado",
      sku: "10089",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baasto",
      sku: "10033",
      price: 0,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baasto iyo Bariis saani",
      sku: "10220",
      price: 1.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baasto saldaato",
      sku: "10084",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baasto Saldato",
      sku: "1",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baasto Tuna",
      sku: "10042",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baasto tuno",
      sku: "10204",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Babaay (Papaya)",
      sku: "10136",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Bajiya",
      sku: "10019",
      price: 0.2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Bariis Macaye",
      sku: "10062",
      price: 1.4,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Bariis saldaato",
      sku: "10201",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Bariis tuuno",
      sku: "10203",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baris",
      sku: "10034",
      price: 0.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baris Saldato",
      sku: "10074",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Baris Tuna",
      sku: "10108",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Battiq (Canteloupe)",
      sku: "10143",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer ari baasto",
      sku: "10150",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer Ari Baasto Iyo Bariis",
      sku: "10189",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer ari bariis",
      sku: "10342",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer ari halfdheri baasto",
      sku: "10113",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer ari rooti",
      sku: "10214",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer ari saxan dheeri",
      sku: "10119",
      price: 5.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer hashi",
      sku: "10198",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer Iyo Canjeero",
      sku: "10041",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Beer seeko",
      sku: "10081",
      price: 3.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biscuit",
      sku: "10156",
      price: 1,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biscuit",
      sku: "10157",
      price: 2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biscuit box",
      sku: "10229",
      price: 0.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biscuit timir",
      sku: "10055",
      price: 0.6,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biyo dhexe",
      sku: "10097",
      price: 0.4,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biyo waawayn",
      sku: "10122",
      price: 1,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Biyo yar",
      sku: "10132",
      price: 0.2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Bur",
      sku: "10020",
      price: 0.2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Caag Caano geel",
      sku: "10058",
      price: 2.5,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Caano Moos",
      sku: "10022",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cafe Latte",
      sku: "10008",
      price: 1,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Caffe late geel",
      sku: "10184",
      price: 1.5,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cake",
      sku: "10059",
      price: 0.7,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cambe (Mango)",
      sku: "10135",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Canjeelo",
      sku: "10216",
      price: 0.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Canjeero",
      sku: "10045",
      price: 0.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Canno Buro  sharab",
      sku: "10349",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cappuccino",
      sku: "10007",
      price: 1,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cappuccino Ari",
      sku: "10009",
      price: 1.5,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cappuccino buro saffari",
      sku: "10051",
      price: 1.2,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cappuccino Geel",
      sku: "10012",
      price: 1.5,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cappuccino geel safaari",
      sku: "10205",
      price: 1.7,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cappuccino Geel Safari",
      sku: "10141",
      price: 1.7,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Baasto",
      sku: "10350",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Barris",
      sku: "10231",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Burger",
      sku: "10023",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Complete",
      sku: "10029",
      price: 12,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken faxis",
      sku: "10064",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken jaax",
      sku: "10031",
      price: 6,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Legs",
      sku: "10028",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs 1 pieces",
      sku: "10060",
      price: 1.5,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs baasto",
      sku: "10118",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs bariis",
      sku: "10117",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs half dheri iswedaar",
      sku: "10124",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs jabaati",
      sku: "10227",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs pancake",
      sku: "10126",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs safari",
      sku: "10148",
      price: 4.2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken legs seeko",
      sku: "10068",
      price: 3.2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Masala",
      sku: "10096",
      price: 1,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chicken Sharwama",
      sku: "10026",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Chips",
      sku: "10086",
      price: 1,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Cocktail",
      sku: "10347",
      price: 1.5,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Coco-Cola",
      sku: "10139",
      price: 1,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Coffee Cup",
      sku: "10099",
      price: 3,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Crispy",
      sku: "10077",
      price: 0,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Daawo Tea",
      sku: "10013",
      price: 1.5,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Diger shidan",
      sku: "10121",
      price: 1.5,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Digir",
      sku: "10035",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Doorshe",
      sku: "10021",
      price: 0.5,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Egg Burger",
      sku: "10025",
      price: 2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fanto",
      sku: "10092",
      price: 1,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Feeto",
      sku: "10050",
      price: 3,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fish Burger",
      sku: "10001",
      price: 2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fish Sharwama",
      sku: "10049",
      price: 2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "FOOTBALL MATCH",
      sku: "10159",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10160",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10161",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10162",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10163",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10164",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10165",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10166",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10167",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10168",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10169",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10170",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10171",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10172",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10173",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10174",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10175",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10176",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10177",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10178",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10179",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10180",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10181",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "nan",
      sku: "10182",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fruit batiiq",
      sku: "10115",
      price: 2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fruit canbe",
      sku: "10123",
      price: 2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fruit canbo",
      sku: "10133",
      price: 1.5,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fruit Mix",
      sku: "10014",
      price: 3,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fruit qare",
      sku: "10015",
      price: 1.5,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Fruit(qara&moos)",
      sku: "10078",
      price: 2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Furulaato",
      sku: "10151",
      price: 3,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn baasto",
      sku: "10207",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn baasto saldaato",
      sku: "10127",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn bariis",
      sku: "10208",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn half dheeri oo bariis ah",
      sku: "10063",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn half dheri",
      sku: "10215",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn saldato",
      sku: "10080",
      price: 5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn Saxan dheeri",
      sku: "10343",
      price: 5.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn saxan dheri bariis",
      sku: "10210",
      price: 5.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafayn saxandheeri baasto",
      sku: "10209",
      price: 5.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafeyn baasto",
      sku: "10046",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafeyn bariis",
      sku: "10054",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hafeyn Seeko",
      sku: "10221",
      price: 3.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Half Bur",
      sku: "10105",
      price: 14,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Half Caano geel",
      sku: "10067",
      price: 1.5,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Haruur",
      sku: "10037",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Haruur moos leh",
      sku: "10039",
      price: 2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Haruur shidan",
      sku: "10038",
      price: 1.5,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hayat Cooking Oil",
      sku: "10057",
      price: 4.5,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hubaal 350ml",
      sku: "10006",
      price: 0.2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hubaal(350Ml)",
      sku: "10111",
      price: 4.4,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Hubaal(800Ml)",
      sku: "10237",
      price: 4.4,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Ice Cafe",
      sku: "10076",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Jabati",
      sku: "10065",
      price: 0.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kalaawi",
      sku: "10044",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kalaawi baasto",
      sku: "10010",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kalaawi half dheri",
      sku: "10128",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kalaawi Jabti",
      sku: "10346",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kalawi Seeko",
      sku: "10236",
      price: 3.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaliwai Bariis",
      sku: "10100",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaliwai canjeero",
      sku: "10230",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaluun",
      sku: "10147",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaluun",
      sku: "10225",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaluun half dheeri",
      sku: "10352",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaluun saxan dheeri",
      sku: "10192",
      price: 5.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaluun seeko",
      sku: "10131",
      price: 3.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kaykay tuna",
      sku: "10047",
      price: 2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke",
      sku: "10073",
      price: 0.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke beer",
      sku: "10093",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke beer ari safari",
      sku: "10211",
      price: 4.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke Kalaawi",
      sku: "10193",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke kalaawi",
      sku: "10200",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke suqaar safaari",
      sku: "10072",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke suqar ceesh dheri",
      sku: "10106",
      price: 4.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke suuqar",
      sku: "10217",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke tuno",
      sku: "10116",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keeke wadani",
      sku: "10223",
      price: 1.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Keke beer",
      sku: "10145",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Ketchup",
      sku: "10017",
      price: 2,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kulaan Baasto",
      sku: "10186",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kulaan Baasto saladato",
      sku: "10195",
      price: 4.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kulaan Baris",
      sku: "10153",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kulaan Half Dheeri",
      sku: "10351",
      price: 4.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kuulan",
      sku: "10040",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Kuulan Bariis",
      sku: "10222",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Lemon Tea",
      sku: "10134",
      price: 0.6,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Liin Dhanaan (Lemonade)",
      sku: "10142",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Liin Macaan(Orange)",
      sku: "10146",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Lipton Tea",
      sku: "10000",
      price: 0.4,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Malab",
      sku: "10109",
      price: 0.5,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Mango Calmbe",
      sku: "10348",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Meat Burger",
      sku: "10024",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Meat Masala",
      sku: "10098",
      price: 1,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Meat rooti",
      sku: "10114",
      price: 2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Meat sharwama",
      sku: "10071",
      price: 4,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Mirinda",
      sku: "10056",
      price: 0.8,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Moos",
      sku: "10016",
      price: 0.5,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Najma Shampoo(1L)",
      sku: "10239",
      price: 1.5,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Najma Shampoo(2L)",
      sku: "10233",
      price: 2.6,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Najma Shampoo(3L)",
      sku: "10240",
      price: 3.6,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Najma Shampoo(500Ml)",
      sku: "10235",
      price: 1,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "NesCafe Original 3in1",
      sku: "10094",
      price: 6,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Pancake",
      sku: "10085",
      price: 0.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Pancake beer ari",
      sku: "10226",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Pancake suqaar",
      sku: "10083",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Pepsi",
      sku: "10138",
      price: 0.8,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Plastic Chairs",
      sku: "10087",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Plastic Chairs",
      sku: "10140",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Popcorn",
      sku: "10027",
      price: 1.2,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Qare (Watermelon)",
      sku: "10043",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Qare iyo Liin macaan",
      sku: "10187",
      price: 1.2,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Qaxawa",
      sku: "10120",
      price: 0.8,
      cost: 0,
      categoryId: Coffee.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Raaxo (250ml)",
      sku: "10130",
      price: 0.2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Raaxo (800ml)",
      sku: "10129",
      price: 0.4,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Rani",
      sku: "10137",
      price: 0.8,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Roos",
      sku: "10030",
      price: 7,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Roos baasto safari",
      sku: "10212",
      price: 7.4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Roos half dheeri",
      sku: "10079",
      price: 7.8,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Roos pancake",
      sku: "10112",
      price: 7,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Roos saxan dheeri",
      sku: "10224",
      price: 8.6,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Roos seeko",
      sku: "10196",
      price: 6.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Root",
      sku: "10053",
      price: 0.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Rooti Suuqar",
      sku: "10199",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saani Baasto Saldaato",
      sku: "10154",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saani Baasto saldato Safari",
      sku: "10241",
      price: 2.2,
      cost: 0,
      categoryId: FastFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saani Bariis iyo Baasto Tuna",
      sku: "10183",
      price: 3,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saani Bariis Saldato",
      sku: "10194",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saani Bariis Tuna",
      sku: "10190",
      price: 3,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saani Baris",
      sku: "10155",
      price: 1.6,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Salbuko",
      sku: "10036",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Salbuko Moos Leh",
      sku: "10234",
      price: 1.5,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Salool",
      sku: "10075",
      price: 0.5,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Sambus",
      sku: "10018",
      price: 0.25,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Sareen safari",
      sku: "10353",
      price: 1.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saxan baasto saldaato",
      sku: "10228",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saxan saldaato bariis",
      sku: "10202",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Saxan tuno",
      sku: "10206",
      price: 3,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaani",
      sku: "10191",
      price: 0.8,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaax Ari",
      sku: "10011",
      price: 1,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaax Bigees",
      sku: "10002",
      price: 0.4,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaax Boore",
      sku: "10091",
      price: 0.4,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaax booro safari",
      sku: "10052",
      price: 0.6,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaax Caano geel safari",
      sku: "10149",
      price: 1.2,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shaax Geel",
      sku: "10003",
      price: 1,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shashuko",
      sku: "10185",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Shax boore safari",
      sku: "10213",
      price: 0.6,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Sonkor half",
      sku: "10104",
      price: 15,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Special Mint",
      sku: "10090",
      price: 1.7,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Sprite",
      sku: "10048",
      price: 0.8,
      cost: 0,
      categoryId: drinks.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Star Tissue",
      sku: "10102",
      price: 2,
      cost: 0,
      categoryId: Store.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suqaar",
      sku: "10032",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suqaar canjeelo",
      sku: "10197",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suqaar Canjeero",
      sku: "10345",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suqaar pancake",
      sku: "10232",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suqaar seeko",
      sku: "10082",
      price: 3.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suuqar Jabti",
      sku: "10107",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Suuqar rooti",
      sku: "10152",
      price: 4,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Takeaway",
      sku: "10144",
      price: 0.2,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Takeaway",
      sku: "10218",
      price: 0.2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Takeaway Cups",
      sku: "10061",
      price: 0.2,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Tangawizi",
      sku: "10005",
      price: 1.5,
      cost: 0,
      categoryId: Tea.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Tissue",
      sku: "10242",
      price: 0,
      cost: 0,
      categoryId: Store.id,
      isActive: false,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Tuna",
      sku: "10188",
      price: 1,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Ukun kaliya",
      sku: "10069",
      price: 2,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Umuleed",
      sku: "10110",
      price: 2.5,
      cost: 0,
      categoryId: SomailFood.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
    {
      name: "Xalwo",
      sku: "10158",
      price: 2,
      cost: 0,
      categoryId: Macmacaan.id,
      isActive: true,
      trackStock: false,
      stockQty: 0,
    },
  ];

  await prisma.product.createMany({
  data: productSeedData,
  skipDuplicates: true,
})

  // -----------------------------
  // Sample order (no tax)
  // -----------------------------
 const table1 = tableRows[0] ?? null

console.log("table count:", tableRows.length)
console.log("first table:", table1)

if (!table1) {
  throw new Error("No table found for seeded dine-in order")
}



  // -----------------------------
  // Shift
  // -----------------------------


  console.log("✅ Seed completed (no tax).");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
